name: Test
on: [pull_request, push]
jobs:
  test:
    container:
      image: ruby:${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.1"]
        appraisal:
          - jekyll-35
          - jekyll-36
          - jekyll-37
          - jekyll-38
          - jekyll-39
          - jekyll-40
          - jekyll-41
          - jekyll-42
          - jekyll-43
        exclude:
          # To prevent 'cannot load such file -- rexml/parsers/baseparser'
          - ruby: "3.1"
            appraisal: jekyll-35
          - ruby: "3.1"
            appraisal: jekyll-36
          - ruby: "3.1"
            appraisal: jekyll-37
          - ruby: "3.1"
            appraisal: jekyll-38
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: gem update && bundle install
      - name: Install dependencies for each appraisal
        run: bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rake test
