name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    container:
      image: ruby:${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.1", "3.2"]
        appraisal:
          - jekyll-35
          - jekyll-36
          - jekyll-37
          - jekyll-38
          - jekyll-39
          - jekyll-40
          - jekyll-41
          - jekyll-42
          - jekyll-43
        exclude:
          # To prevent 'cannot load such file -- rexml/parsers/baseparser'
          - ruby: "3.1"
            appraisal: jekyll-35
          - ruby: "3.1"
            appraisal: jekyll-36
          - ruby: "3.1"
            appraisal: jekyll-37
          - ruby: "3.1"
            appraisal: jekyll-38
          - ruby: "3.2"
            appraisal: jekyll-35
          - ruby: "3.2"
            appraisal: jekyll-36
          - ruby: "3.2"
            appraisal: jekyll-37
          - ruby: "3.2"
            appraisal: jekyll-38
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # See https://github.com/actions/runner-images/issues/6775.
      - name: Suppress 'detected dubious ownership' error
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - if: matrix.ruby == '2.7'
        name: Update RubyGems version
        # sass-embedded 1.57.1, which is one of dependencies of jekyll-sass-converter 3.0,
        # requires rubygems version >= 3.3.22
        # (see https://jekyllrb.com/news/2022/12/21/jekyll-sass-converter-3.0-released/
        #  for the jekyll-sass-converter 3.0 release).
        # Just running `gem update --system` upgrades rubygems version to '>= 2.4',
        # which appraisal 2.4.1 can't work with.
        run: gem update --system 3.3.22
      - name: Install dependencies
        run: bundle install
      - name: Install dependencies for each appraisal
        run: bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rake test
